apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
      - image: shrikumarudupa/user-service
        name: user-service
        ports:
          - containerPort: 8090
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user
  name: user
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: user
  type: NodePort
status:
  loadBalancer: {}